[options]
addons_path = /home/mustafa/telcobright-projects/odoo/odoo-backend/odoo-src/addons,/home/mustafa/telcobright-projects/odoo/odoo-backend/custom-addons
data_dir = /home/mustafa/telcobright-projects/odoo/odoo-backend/data
http_port = 7169
db_host = False
db_port = 5433
db_user = mustafa
db_password = False
admin_passwd = $pbkdf2-sha512$600000$KsXYu7d2bi3F.D9nzJlzzg$819lanbp8il1zAayaAB98v2U.xjn3mt/QJbkDLl0lMLN..qMNUznV.L0CJ5uPP0/4BWktNOyZpbVlID0iaN0JA
workers = 0
max_cron_threads = 1
limit_memory_hard = 1677721600
limit_memory_soft = 629145600
limit_time_cpu = 600
limit_time_real = 1200
log_level = info

