from . import res_company
from . import res_partner
from . import product_template
from . import product_product
from . import account_move
from . import account_payment
from . import sale_order_line
from . import kb_sync_log
from . import product_rate_history
