server:
  port: 8180

odoo:
  url: http://127.0.0.1:7169
  db: odoo_billing
  username: admin
  password: admin

killbill:
  url: http://127.0.0.1:18080
  username: admin
  password: password

spring:
  application:
    name: PLATFORM-API
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7104/realms/telcobright

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: localhost
