"""
Rename all model tables to plane_<original>_table prefix.

Part of the unified-DB-with-Odoo plan: prevents future name collisions when
Plane and Odoo schemas live in the same Postgres database per tenant.
"""
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="device",
            table="plane_devices",
        ),
        migrations.AlterModelTable(
            name="devicesession",
            table="plane_device_sessions",
        ),
        migrations.AlterModelTable(
            name="sticky",
            table="plane_stickies",
        ),
        migrations.AlterModelTable(
            name="exporterhistory",
            table="plane_exporters",
        ),
        migrations.AlterModelTable(
            name="session",
            table="plane_sessions",
        ),
        migrations.AlterModelTable(
            name="state",
            table="plane_states",
        ),
        migrations.AlterModelTable(
            name="issueview",
            table="plane_issue_views",
        ),
        migrations.AlterModelTable(
            name="notification",
            table="plane_notifications",
        ),
        migrations.AlterModelTable(
            name="usernotificationpreference",
            table="plane_user_notification_preferences",
        ),
        migrations.AlterModelTable(
            name="emailnotificationlog",
            table="plane_email_notification_logs",
        ),
        migrations.AlterModelTable(
            name="webhook",
            table="plane_webhooks",
        ),
        migrations.AlterModelTable(
            name="webhooklog",
            table="plane_webhook_logs",
        ),
        migrations.AlterModelTable(
            name="projectwebhook",
            table="plane_project_webhooks",
        ),
        migrations.AlterModelTable(
            name="userfavorite",
            table="plane_user_favorites",
        ),
        migrations.AlterModelTable(
            name="user",
            table="plane_users",
        ),
        migrations.AlterModelTable(
            name="profile",
            table="plane_profiles",
        ),
        migrations.AlterModelTable(
            name="account",
            table="plane_accounts",
        ),
        migrations.AlterModelTable(
            name="page",
            table="plane_pages",
        ),
        migrations.AlterModelTable(
            name="pagelog",
            table="plane_page_logs",
        ),
        migrations.AlterModelTable(
            name="pagelabel",
            table="plane_page_labels",
        ),
        migrations.AlterModelTable(
            name="projectpage",
            table="plane_project_pages",
        ),
        migrations.AlterModelTable(
            name="pageversion",
            table="plane_page_versions",
        ),
        migrations.AlterModelTable(
            name="issue",
            table="plane_issues",
        ),
        migrations.AlterModelTable(
            name="issueblocker",
            table="plane_issue_blockers",
        ),
        migrations.AlterModelTable(
            name="issuerelation",
            table="plane_issue_relations",
        ),
        migrations.AlterModelTable(
            name="issuemention",
            table="plane_issue_mentions",
        ),
        migrations.AlterModelTable(
            name="issueassignee",
            table="plane_issue_assignees",
        ),
        migrations.AlterModelTable(
            name="issuelink",
            table="plane_issue_links",
        ),
        migrations.AlterModelTable(
            name="issueattachment",
            table="plane_issue_attachments",
        ),
        migrations.AlterModelTable(
            name="issueactivity",
            table="plane_issue_activities",
        ),
        migrations.AlterModelTable(
            name="issuecomment",
            table="plane_issue_comments",
        ),
        migrations.AlterModelTable(
            name="issuelabel",
            table="plane_issue_labels",
        ),
        migrations.AlterModelTable(
            name="issuesequence",
            table="plane_issue_sequences",
        ),
        migrations.AlterModelTable(
            name="issuesubscriber",
            table="plane_issue_subscribers",
        ),
        migrations.AlterModelTable(
            name="issuereaction",
            table="plane_issue_reactions",
        ),
        migrations.AlterModelTable(
            name="commentreaction",
            table="plane_comment_reactions",
        ),
        migrations.AlterModelTable(
            name="issuevote",
            table="plane_issue_votes",
        ),
        migrations.AlterModelTable(
            name="issueversion",
            table="plane_issue_versions",
        ),
        migrations.AlterModelTable(
            name="issuedescriptionversion",
            table="plane_issue_description_versions",
        ),
        migrations.AlterModelTable(
            name="intake",
            table="plane_intakes",
        ),
        migrations.AlterModelTable(
            name="intakeissue",
            table="plane_intake_issues",
        ),
        migrations.AlterModelTable(
            name="apitoken",
            table="plane_api_tokens",
        ),
        migrations.AlterModelTable(
            name="apiactivitylog",
            table="plane_api_activity_logs",
        ),
        migrations.AlterModelTable(
            name="fileasset",
            table="plane_file_assets",
        ),
        migrations.AlterModelTable(
            name="importer",
            table="plane_importers",
        ),
        migrations.AlterModelTable(
            name="description",
            table="plane_descriptions",
        ),
        migrations.AlterModelTable(
            name="descriptionversion",
            table="plane_description_versions",
        ),
        migrations.AlterModelTable(
            name="project",
            table="plane_projects",
        ),
        migrations.AlterModelTable(
            name="projectmemberinvite",
            table="plane_project_member_invites",
        ),
        migrations.AlterModelTable(
            name="projectmember",
            table="plane_project_members",
        ),
        migrations.AlterModelTable(
            name="projectidentifier",
            table="plane_project_identifiers",
        ),
        migrations.AlterModelTable(
            name="projectdeployboard",
            table="plane_project_deploy_boards",
        ),
        migrations.AlterModelTable(
            name="projectpublicmember",
            table="plane_project_public_members",
        ),
        migrations.AlterModelTable(
            name="projectuserproperty",
            table="plane_project_user_properties",
        ),
        migrations.AlterModelTable(
            name="draftissue",
            table="plane_draft_issues",
        ),
        migrations.AlterModelTable(
            name="draftissueassignee",
            table="plane_draft_issue_assignees",
        ),
        migrations.AlterModelTable(
            name="draftissuelabel",
            table="plane_draft_issue_labels",
        ),
        migrations.AlterModelTable(
            name="draftissuemodule",
            table="plane_draft_issue_modules",
        ),
        migrations.AlterModelTable(
            name="draftissuecycle",
            table="plane_draft_issue_cycles",
        ),
        migrations.AlterModelTable(
            name="socialloginconnection",
            table="plane_social_login_connections",
        ),
        migrations.AlterModelTable(
            name="userrecentvisit",
            table="plane_user_recent_visits",
        ),
        migrations.AlterModelTable(
            name="estimate",
            table="plane_estimates",
        ),
        migrations.AlterModelTable(
            name="estimatepoint",
            table="plane_estimate_points",
        ),
        migrations.AlterModelTable(
            name="deployboard",
            table="plane_deploy_boards",
        ),
        migrations.AlterModelTable(
            name="issuetype",
            table="plane_issue_types",
        ),
        migrations.AlterModelTable(
            name="projectissuetype",
            table="plane_project_issue_types",
        ),
        migrations.AlterModelTable(
            name="module",
            table="plane_modules",
        ),
        migrations.AlterModelTable(
            name="modulemember",
            table="plane_module_members",
        ),
        migrations.AlterModelTable(
            name="moduleissue",
            table="plane_module_issues",
        ),
        migrations.AlterModelTable(
            name="modulelink",
            table="plane_module_links",
        ),
        migrations.AlterModelTable(
            name="moduleuserproperties",
            table="plane_module_user_properties",
        ),
        migrations.AlterModelTable(
            name="cycle",
            table="plane_cycles",
        ),
        migrations.AlterModelTable(
            name="cycleissue",
            table="plane_cycle_issues",
        ),
        migrations.AlterModelTable(
            name="cycleuserproperties",
            table="plane_cycle_user_properties",
        ),
        migrations.AlterModelTable(
            name="workspace",
            table="plane_workspaces",
        ),
        migrations.AlterModelTable(
            name="workspacemember",
            table="plane_workspace_members",
        ),
        migrations.AlterModelTable(
            name="workspacememberinvite",
            table="plane_workspace_member_invites",
        ),
        migrations.AlterModelTable(
            name="team",
            table="plane_teams",
        ),
        migrations.AlterModelTable(
            name="workspacetheme",
            table="plane_workspace_themes",
        ),
        migrations.AlterModelTable(
            name="workspaceuserproperties",
            table="plane_workspace_user_properties",
        ),
        migrations.AlterModelTable(
            name="workspaceuserlink",
            table="plane_workspace_user_links",
        ),
        migrations.AlterModelTable(
            name="workspacehomepreference",
            table="plane_workspace_home_preferences",
        ),
        migrations.AlterModelTable(
            name="workspaceuserpreference",
            table="plane_workspace_user_preferences",
        ),
        migrations.AlterModelTable(
            name="label",
            table="plane_labels",
        ),
        migrations.AlterModelTable(
            name="analyticview",
            table="plane_analytic_views",
        ),
        migrations.AlterModelTable(
            name="slackprojectsync",
            table="plane_slack_project_syncs",
        ),
        migrations.AlterModelTable(
            name="githubrepository",
            table="plane_github_repositories",
        ),
        migrations.AlterModelTable(
            name="githubrepositorysync",
            table="plane_github_repository_syncs",
        ),
        migrations.AlterModelTable(
            name="githubissuesync",
            table="plane_github_issue_syncs",
        ),
        migrations.AlterModelTable(
            name="githubcommentsync",
            table="plane_github_comment_syncs",
        ),
        migrations.AlterModelTable(
            name="integration",
            table="plane_integrations",
        ),
        migrations.AlterModelTable(
            name="workspaceintegration",
            table="plane_workspace_integrations",
        ),
    ]
