tenant:
  name: BTCL
  slug: btcl
  profile: staging
  environment: staging

branding:
  display-name: BTCL
  short-name: TB
  theme: green

killbill:
  url: http://killbill-staging.internal:18080
  api-key: btcl
  api-secret: btcl-secret
  username: admin
  password: ${KB_PASSWORD:password}

catalog:
  url: http://odoo-staging.internal:7169
  db: odoo_billing
  partner-id: 8

products: {}
